#!/bin/bash

arg=$1

[ ! -n "$arg" ] && echo "Please provide the package name to uninstall" && exit 1;

[ ! -n "$(which $arg)" ] && echo "Package not found on the system.." && exit 1;

uninstall(){
	sudo apt remove -y $arg;
	sudo apt autoremove;
	sudo apt clean;
	exit 0;
}

uninstall_all(){
	sudo apt  purge -y $arg;
	sudo apt autoremove;
	sudo apt clean
	exit 0;
}

echo -n "Do you want to completely remove with configuration files? (y/n)";

read conf;

[ "$conf" = "Y" -o "$conf" = "y" -o "$conf" = "Yes" -o "$conf" = "yes" ] && uninstall_all;

[ "$conf" = "N" -o "$conf" = "n" -o "$conf" = "No" -o "$conf" = "no" ] && uninstall;